### ISSUE TITLE
thirdScriptError: TypeError: Cannot read property 'list' of undefined

### ISSUE THREAD

**Issue by rrryan2016** [SuRuiGit/wxapp-customTabbar#6]
很感谢您的思路！

我按照您的项目主页的步骤，以及其他站点的讲解之后，编译时出现了以下的问题
`thirdScriptError
Cannot read property 'list' of undefined;at App editTabbar function
TypeError: Cannot read property 'list' of undefined`
还麻烦请教一下您点拨一下，谢谢了。

此外还有以下的疑问：
1. 该处 https://github.com/SuRuiGit/wxapp-customTabbar/blob/09106f10474f19035da01e1ee715e13ad11d3675/tabbarDemo/app.js#L53 与 https://blog.csdn.net/dt1991524/article/details/82699682 中的if语句不一样。到底应该如何使用呢？
2. 此处 https://github.com/SuRuiGit/wxapp-customTabbar/blob/09106f10474f19035da01e1ee715e13ad11d3675/tabbarDemo/app.js#L65 应该是写`tabbar`还是`tabBar`呢？
3. 可以分享一下您自定义navBar的代码吗？因为我也想左上角实现页面的后退。

打扰了，再次感谢您。

**Comment by SuRuiGit** [comment]
报错可能是你没写这句话let tabbar = this.globalData.tabBar; 第一个问题只是写法不一样，语句实现是一样的，第二个问题globalData里用的是tabBar，最后现在官网已经出自定义tabbar了，自定义navbar你也可以去官网看看
